allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - "@esbuild/darwin-arm64"
  - "@next/swc-darwin-arm64"
  - "@rolldown/binding-darwin-arm64"
  - esbuild
  - lightningcss
  - sharp
  - unrs-resolver
  - workerd
